apiVersion: v1
kind: ConfigMap
metadata:
  name: external-services-config
  namespace: lugx-gaming-staging
data:
  # AWS RDS PostgreSQL Configuration
  POSTGRES_HOST: "REPLACE_WITH_RDS_ENDPOINT"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "lugx_gaming_staging"
  POSTGRES_SSLMODE: "require"
  
  # Environment specific settings
  ENVIRONMENT: "staging"
  LOG_LEVEL: "DEBUG"
  
  # Analytics ClickHouse Configuration
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DB: "analytics"

---
apiVersion: v1
kind: Secret
metadata:
  name: external-db-secrets
  namespace: lugx-gaming-staging
type: Opaque
data:
  # These will be replaced by the CI/CD pipeline with actual AWS RDS credentials
  postgres-user: REPLACE_WITH_BASE64_USERNAME
  postgres-password: REPLACE_WITH_BASE64_PASSWORD

---
# Resource quotas for staging namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lugx-gaming-quota
  namespace: lugx-gaming-staging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "15"
    services: "8"
