apiVersion: v1
kind: ConfigMap
metadata:
  name: external-services-config
  namespace: lugx-gaming-dev
data:
  # AWS RDS PostgreSQL Configuration
  POSTGRES_HOST: "REPLACE_WITH_RDS_ENDPOINT"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "lugx_gaming_dev"
  POSTGRES_SSLMODE: "require"
  
  # Environment specific settings
  ENVIRONMENT: "development"
  LOG_LEVEL: "DEBUG"
  
  # Analytics ClickHouse Configuration
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DB: "analytics"

---
apiVersion: v1
kind: Secret
metadata:
  name: external-db-secrets
  namespace: lugx-gaming-dev
type: Opaque
data:
  # These will be replaced by the CI/CD pipeline with actual AWS RDS credentials
  postgres-user: REPLACE_WITH_BASE64_USERNAME
  postgres-password: REPLACE_WITH_BASE64_PASSWORD

---
# Resource quotas for development namespace  
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lugx-gaming-quota
  namespace: lugx-gaming-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "10"
    services: "5"
